name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  rabota:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
       submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        sudo apt-get install -y cmake lcov gcovr python3-pip
        pip install gcovr
      #  sudo apt-get install google-mock
      #  sudo apt-get install libgtest-dev
      # sudo apt-get install libtbb-dev
      #  sudo apt-get install cmake
      #  cd /usr/src/googletest/
      #  sudo mkdir build
      #  cd build
      #  sudo cmake ..
      # sudo make
      #  sudo cp lib/* /usr/lib

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      #run: |
        #cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build/tests
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Install GTest (if not bundled)
      run: |
        sudo apt-get install -y libgtest-dev

    - name: Run tests
      run: |
        cd build/tests && ctest --output-on-failure && ${{github.workspace}}/build/tests/testion
        
    #- name: npm install
      #run: npm install

    #- name: Test
      #run: make test-coverage
    
    - name: Use Node.js 16.16.0
      uses: actions/setup-node@v3
      with:
        node-version: 16.16.0
    - run: npm@5 ci
    - run: npm run build --if-present
    - run: npm run coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}


    




